### ISSUE TITLE
[typo] README plus example added wrong

### ISSUE THREAD

**Issue by adamschwartz** [adobe/ferrum#17]
Minor typo:

> ```js
> list(map([1,2,3], plus(2))); // => [2,3,4]
> ```

Source: https://github.com/adobe/ferrum/blame/fbcef1ed40084db5693ce8494af5cad5490f47ca/README.md#L525

Should be:

```js
list(map([1,2,3], plus(2))); // => [3,4,5]
```

**Comment by koraa** [comment]
Thanks for the good catch. Fixed in 7450e899f910fdad375d2a3ddda4fda522ac9999 !
