### ISSUE TITLE
AssertSequenceEquals is not a function

### ISSUE THREAD

**Issue by James-Quigley** [adobe/ferrum#18]
**Description**
When running the first example in the Readme, it uses `assertSequenceEquals`, which does not exist on the ferrum object

**To Reproduce**
1. Run the first example in the readme

**Expected behavior**
Two maps and an assert

**Version:**
ferrum: 0.3.2

**Comment by koraa** [comment]
Argh! Thanks for testing this!
Seems the auto publish to NPM has some problems…

**Comment by koraa** [comment]
Fixed as of fbabd7a4adbc261c54d7f4e6c33ca9bf8ba8ff6b
