### ISSUE TITLE
Take is broken on plain arrays?

### ISSUE THREAD

**Issue by tobia** [adobe/ferrum#193]
**Description**
`take` does not seem to work if the data argument is a plain JS array.

**To Reproduce**
```
> take([1,2,3,4], 3)
[ 1, 1, 1 ]
```

**Expected behavior**
Unless I'm misunderstanding something, I expected to get `[1, 2, 3]`

**Version:**
Ferrum 1.9.0 on Node 14.16.0

**Comment by koraa** [comment]
Oh yeah, the implementation uses next() without iter…fantastic catch, thank you!
You seem to be doing some thorough checking of the library, thank you! I do appreciate it!
