### ISSUE TITLE
typo in docs: compose

### ISSUE THREAD

**Issue by imcotton** [adobe/ferrum#25]
**Expected behavior**
```diff
- // => 18
+ // => 14
```

**Additional context**

https://github.com/adobe/ferrum/blob/7eb22eab1e541b2a36db4519124f7c5890a20f7f/src/functional.js#L92-L97

**Comment by imcotton** [comment]
Wait, I've just realized the `compose` in **ferrum** not been performed **right-to-left** as traditional function composition? 😕

**Comment by koraa** [comment]
Yes, it's performed top to bottom; this is one of the places where ferrum tries to strike a balance between what is traditional in functional programming and what makes sense in javascript. In javascript a dot free style is much harder to achieve and making it understandable to js programmers who are not fluent in haskell or other fully functional languages is even harder…
Here compose() is intended more as a `pipe()` that does not have it's initial argument…

But thanks for checking it out thougj, the docs might need improvement to make that even clearer :)
