### ISSUE TITLE
Fix typos and improve README

### ISSUE THREAD

**Issue by prashcr** [adobe/ferrum#39]
Fix the following issues in the README:

* It contains typos
* Update capitalization of programming languages e.g. Rust, Python, JavaScript
* Remove references to Typeclasses, as that is a slightly different concept from Scala/Haskell, not Rust
* Add a link to Rust Traits example for people that are unfamiliar with Rust

**Comment by koraa** [comment]
Thanks for your contribution! I am afraid I am myself quite dreadful at spotting typos (and quite good at creating them ;) ). Could you please provide a PR fixing them?

 Could you please explain in what important way type classes differ? As far as I am concerned traits are basically type classes made to function in  rust…
Granted, they are not completely the same, but neither are the Traits provided in here the same as the ones provided by rust, but all three aim at providing a mechanism for ad-hoc polymorphism…

**Comment by prashcr** [comment]
I'm not very familiar with either Rust or Haskell, but this question seems to have a couple of good answers: https://stackoverflow.com/questions/28123453/what-is-the-difference-between-traits-in-rust-and-typeclasses-in-haskell

From my personal experience, I read the README, googled "rust typeclasses" then got confused about why all the results mentioned Haskell and that there was no authoritative Rust doc that referrred to it as "typeclasses"

**Comment by koraa** [comment]
Yeah, the points from the link are definitely valid! Rust traits and haskell type classes however are more similar than the construction in ferrum starting with the fact that this repo uses runtime polymorphism, not compile time…

But your point is well taken, this *does* need some clarifying in the doc…
