### ISSUE TITLE
Use Adobe Bot Credentials for Semantic Release

### ISSUE THREAD

**Issue by tripodsan** [adobe/ferrum#5]
@trieloff Can you please add the proper config in circle CI ? thanks.

**Comment by tripodsan** [comment]
Actually, I just realized that the package is released without the `@adobe/` scope.
@trieloff @koraa Should we move it there? 

Alternatively, @koraa can add the adobe bot (`adobe-admin <grp-opensourceoffice@adobe.com>`) as owner to the package:

```
$ npm owner ls ferrum
korra <npmjs.karo@cupdev.net>
```

see https://docs.npmjs.com/cli/owner

**Comment by trieloff** [comment]
@koraa I'd be +1 with renaming it to `@adobe/ferrum` and I'll copy the tokens in CircleCI right away.

**Comment by trieloff** [comment]
`GH_TOKEN` and `NPM_TOKEN` have been set up.

**Comment by koraa** [comment]
I'd prefer using the plain ferrum name, since it's

**Comment by tripodsan** [comment]
> npm add owner adobe-admin
> npm remove owner koraa

I wouldn't remove you...otherwise we're only left with the bot account...which might be a problem.
@trieloff I think it's also possible to add the entire helix team, right?

eg. when I do a 
```
$ npm owner ls @adobe/helix-simulator
```
I see many users - and I dont think they we all added indicidually.

**Comment by koraa** [comment]
I think (not quite sure, `$ npm owner ls` isn't up to date yet) I've added adobe-admin; I've also added tripod, trieloff and rofe for truck factor reduction. Not sure if I should add all the other names; seems like a lot…I could write a script of course…

**Comment by tripodsan** [comment]
hmm, so far I see:

```
$ npm owner ls ferrum
korra <npmjs.karo@cupdev.net>
rofe <npm@rofe.com>
```

**Comment by trieloff** [comment]
Helix Simulator is part of the `@adobe` namespace, so anyone in the NPM Adobe org is a collaborator, which I think is the right way to go

**Comment by koraa** [comment]
@tripodsan Probably needs some time to become active…
